import type { Category, InventoryMutationResult, InventoryValuationReport, ListResponse, Location, Lot, Product, PurchaseOrder, PurchaseOrderLine, ReorderSuggestion, Supplier, TransferResult, User, Warehouse } from "./types";
export class APIError extends Error{readonly status:number;constructor(status:number,message:string){super(message);this.name="APIError";this.status=status}}
type ErrorBody={error?:string};
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const method=(init.method??"GET").toUpperCase();const headers=new Headers(init.headers);headers.set("Accept","application/json");if(init.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");if(!["GET","HEAD","OPTIONS"].includes(method)&&path!=="/api/v1/auth/login")headers.set("X-StockPilot-CSRF","1");const response=await fetch(path,{...init,method,headers,credentials:"include"});if(!response.ok){let message=`Request failed with status ${response.status}.`;try{const body=(await response.json()) as ErrorBody;if(body.error?.trim())message=body.error}catch{}throw new APIError(response.status,message)}if(response.status===204)return undefined as T;return await response.json() as T}
const emptyValuation:InventoryValuationReport={items:[],totals:[]};
export const stockpilotAPI={
 me:()=>request<User>("/api/v1/auth/me"),login:(email:string,password:string)=>request<{user:User;expiresAt:string}>("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})}),logout:()=>request<void>("/api/v1/auth/logout",{method:"POST"}),
 listCategories:()=>request<ListResponse<Category>>("/api/v1/categories"),listSuppliers:()=>request<ListResponse<Supplier>>("/api/v1/suppliers?active=true"),listProducts:(query="")=>request<ListResponse<Product>>(`/api/v1/products?active=false&limit=200&q=${encodeURIComponent(query.trim())}`),
 createProduct:(product:Omit<Product,"id"|"createdAt"|"updatedAt">)=>request<Product>("/api/v1/products",{method:"POST",body:JSON.stringify(product)}),updateProduct:(id:string,product:Omit<Product,"id"|"createdAt"|"updatedAt">)=>request<Product>(`/api/v1/products/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify(product)}),productByBarcode:(barcode:string)=>request<Product>(`/api/v1/products/by-barcode/${encodeURIComponent(barcode.trim())}`),
 listWarehouses:()=>request<ListResponse<Warehouse>>("/api/v1/warehouses?active=true"),listLocations:(warehouseId="")=>request<ListResponse<Location>>(`/api/v1/locations?active=true${warehouseId?`&warehouseId=${encodeURIComponent(warehouseId)}`:""}`),createWarehouse:(warehouse:Omit<Warehouse,"id">)=>request<Warehouse>("/api/v1/warehouses",{method:"POST",body:JSON.stringify(warehouse)}),createLocation:(location:Omit<Location,"id">)=>request<Location>("/api/v1/locations",{method:"POST",body:JSON.stringify(location)}),
 listLots:(productId:string)=>request<ListResponse<Lot>>(`/api/v1/lots?productId=${encodeURIComponent(productId)}&limit=100`),createLot:(lot:Omit<Lot,"id"|"createdAt">)=>request<Lot>("/api/v1/lots",{method:"POST",body:JSON.stringify(lot)}),
 applyMovement:(movement:{productId:string;locationId:string;type:"stock_in"|"stock_out"|"adjustment";quantityDelta:number;lotId?:string;reference?:string;note?:string})=>request<InventoryMutationResult>("/api/v1/inventory/movements",{method:"POST",body:JSON.stringify(movement)}),transfer:(transfer:{productId:string;fromLocationId:string;toLocationId:string;quantity:number;lotId?:string;reference?:string;note?:string})=>request<TransferResult>("/api/v1/inventory/transfers",{method:"POST",body:JSON.stringify(transfer)}),
 listOrders:(status="")=>request<ListResponse<PurchaseOrder>>(`/api/v1/orders?limit=100${status?`&status=${encodeURIComponent(status)}`:""}`),createOrder:(order:{number:string;supplierId:string;warehouseId:string;status:PurchaseOrder["status"];currency:string;expectedAt?:string;notes?:string;lines:Array<Omit<PurchaseOrderLine,"id"|"purchaseOrderId">>})=>request<PurchaseOrder>("/api/v1/orders",{method:"POST",body:JSON.stringify(order)}),receiveOrderLine:(orderId:string,lineId:string,body:{quantity:number;locationId:string;lotId?:string})=>request<PurchaseOrder>(`/api/v1/orders/${encodeURIComponent(orderId)}/lines/${encodeURIComponent(lineId)}/receive`,{method:"POST",body:JSON.stringify(body)}),
 dashboard:async(includeValuation=true)=>{const valuationRequest=includeValuation?request<InventoryValuationReport>("/api/v1/reports/inventory-valuation?limit=100"):Promise.resolve(emptyValuation);const[products,reorderSuggestions,valuation,orders]=await Promise.all([request<ListResponse<Product>>("/api/v1/products?active=true&limit=100"),request<ListResponse<ReorderSuggestion>>("/api/v1/inventory/reorder-suggestions?limit=100"),valuationRequest,request<ListResponse<PurchaseOrder>>("/api/v1/orders?limit=100")]);return{products:products.items??[],reorderSuggestions:reorderSuggestions.items??[],valuation:{items:valuation.items??[],totals:valuation.totals??[]},orders:orders.items??[]}}
};
