import { useCallback, useEffect, useState } from "react";
import { APIError, stockpilotAPI } from "./api";
import type { AuditEvent, User } from "./types";

type Props={user:User;onBack:()=>void;onSessionExpired:()=>void};
export function AuditScreen({user,onBack,onSessionExpired}:Props){
 const[events,setEvents]=useState<AuditEvent[]>([]),[actorId,setActorId]=useState(""),[action,setAction]=useState(""),[entityType,setEntityType]=useState(""),[entityId,setEntityId]=useState(""),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[message,setMessage]=useState("");const limit=50;const canView=user.role!=="operator";
 const load=useCallback(async()=>{if(!canView)return;setLoading(true);try{const result=await stockpilotAPI.listAuditEvents({actorId,action,entityType,entityId,limit,offset});setEvents(result.items??[]);setMessage("")}catch(e){if(e instanceof APIError&&e.status===401){onSessionExpired();return}setMessage(e instanceof Error?e.message:"Could not load audit events.")}finally{setLoading(false)}},[actorId,action,entityId,entityType,offset,canView,onSessionExpired]);
 useEffect(()=>{void load()},[load]);
 function clearFilters(){setActorId("");setAction("");setEntityType("");setEntityId("");setOffset(0)}
 if(!canView)return <main className="catalog-page"><button className="secondary-button" type="button" onClick={onBack}>← Overview</button><section className="panel"><h1>Audit history</h1><p className="muted">Your role does not have permission to view audit history.</p></section></main>;
 return <main className="catalog-page" aria-labelledby="audit-title"><header className="catalog-header"><div><button className="secondary-button" type="button" onClick={onBack}>← Overview</button><p className="eyebrow">Auditability</p><h1 id="audit-title">Audit history</h1><p className="muted">Review completed sensitive mutations with actor, action, entity, request ID, and metadata.</p></div><button className="secondary-button" type="button" onClick={()=>void load()} disabled={loading}>Refresh</button></header>
 {message&&<p className="notice error" role="alert">{message}</p>}
 <section className="panel" aria-label="Audit filters"><div className="form-grid"><label><span>Actor ID</span><input value={actorId} onChange={e=>{setActorId(e.target.value);setOffset(0)}} placeholder="usr_…"/></label><label><span>Action</span><input value={action} onChange={e=>{setAction(e.target.value);setOffset(0)}} placeholder="product.created"/></label><label><span>Entity type</span><input value={entityType} onChange={e=>{setEntityType(e.target.value);setOffset(0)}} placeholder="product"/></label><label><span>Entity ID</span><input value={entityId} onChange={e=>{setEntityId(e.target.value);setOffset(0)}} placeholder="prd_…"/></label></div><div className="form-actions"><button className="secondary-button" type="button" onClick={clearFilters}>Clear filters</button></div></section>
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Events</p><h2>Recent activity</h2></div><span className="count-pill">{events.length}</span></div>{events.length===0&&!loading?<div className="empty-state"><strong>No audit events found</strong><p>Try a broader filter or wait for a completed mutation.</p></div>:<div className="table-wrap"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Entity</th><th>Request ID</th><th>Metadata</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{formatDate(event.occurredAt)}</td><td className="mono">{event.actorId||"system"}</td><td><span className="status-badge good">{event.action}</span></td><td><strong>{event.entityType}</strong><small className="table-secondary">{event.entityId}</small></td><td className="mono">{event.requestId||"—"}</td><td><code className="audit-meta">{formatMetadata(event.metadata)}</code></td></tr>)}</tbody></table></div>}<div className="pager"><button className="secondary-button" type="button" onClick={()=>setOffset(Math.max(0,offset-limit))} disabled={offset===0||loading}>Newer</button><span className="muted">Showing {offset+1}–{offset+events.length}</span><button className="secondary-button" type="button" onClick={()=>setOffset(offset+limit)} disabled={events.length<limit||loading}>Older</button></div></section></main>;
}
function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function formatMetadata(metadata:Record<string,unknown>){try{return JSON.stringify(metadata)}catch{return "{}"}}
