import { useEffect, useMemo, useState, type FormEvent } from "react";
import { APIError, stockpilotAPI } from "./api";
import type { Location, Product, User, Warehouse } from "./types";

type Operation = "stock_in" | "stock_out" | "adjustment" | "transfer";
type Props = { user: User; onBack: () => void; onSessionExpired: () => void };

export function InventoryOperationsScreen({ user, onBack, onSessionExpired }: Props) {
  const [products, setProducts] = useState<Product[]>([]); const [warehouses, setWarehouses] = useState<Warehouse[]>([]); const [locations, setLocations] = useState<Location[]>([]);
  const [operation, setOperation] = useState<Operation>("stock_in"); const [productId, setProductId] = useState(""); const [locationId, setLocationId] = useState(""); const [fromLocationId, setFromLocationId] = useState(""); const [toLocationId, setToLocationId] = useState(""); const [quantity, setQuantity] = useState(1); const [reference, setReference] = useState(""); const [note, setNote] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const canWrite = user.role !== "viewer";

  useEffect(() => { void Promise.all([stockpilotAPI.listProducts(""), stockpilotAPI.listWarehouses(), stockpilotAPI.listLocations()]).then(([p,w,l]) => { setProducts(p.items ?? []); setWarehouses(w.items ?? []); setLocations(l.items ?? []); setProductId(p.items?.[0]?.id ?? ""); setLocationId(l.items?.[0]?.id ?? ""); setFromLocationId(l.items?.[0]?.id ?? ""); setToLocationId(l.items?.[1]?.id ?? ""); setState("ready"); }).catch((error: unknown) => { if (error instanceof APIError && error.status === 401) { onSessionExpired(); return; } setState("error"); setMessage(error instanceof Error ? error.message : "Could not load inventory setup data."); }); }, [onSessionExpired]);
  const selectedProduct = products.find((item) => item.id === productId); const selectedLocation = locations.find((item) => item.id === locationId); const warehouseById = useMemo(() => new Map(warehouses.map((warehouse) => [warehouse.id, warehouse.name])), [warehouses]);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage("");
    if (!canWrite) { setMessage("Your role is read-only for inventory operations."); return; }
    if (!productId) { setMessage("Select a product."); return; }
    if (operation === "adjustment") { if (!Number.isSafeInteger(quantity) || quantity === 0) { setMessage("Adjustment must be a non-zero whole-number delta."); return; } }
    else if (quantity <= 0 || !Number.isSafeInteger(quantity)) { setMessage("Quantity must be a positive whole number."); return; }
    if (operation === "transfer") { if (!fromLocationId || !toLocationId || fromLocationId === toLocationId) { setMessage("Choose two different locations for a transfer."); return; } }
    else if (!locationId) { setMessage("Select a location."); return; }
    setSaving(true);
    try {
      if (operation === "transfer") { const result = await stockpilotAPI.transfer({ productId, fromLocationId, toLocationId, quantity, reference: reference.trim() || undefined, note: note.trim() || undefined }); setMessage(`Transfer ${result.transferId} completed successfully.`); }
      else { const quantityDelta = operation === "stock_out" ? -quantity : quantity; const result = await stockpilotAPI.applyMovement({ productId, locationId, type: operation, quantityDelta, reference: reference.trim() || undefined, note: note.trim() || undefined }); setMessage(`Movement ${result.movementId} recorded. New balance: ${result.balance.quantity.toLocaleString()}.`); }
      setReference(""); setNote("");
    } catch (error: unknown) { if (error instanceof APIError && error.status === 401) { onSessionExpired(); return; } setMessage(error instanceof Error ? error.message : "The inventory operation could not be completed."); }
    finally { setSaving(false); }
  }

  const quantityLabel = operation === "adjustment" ? "Adjustment delta" : operation === "transfer" ? "Transfer quantity" : "Quantity";
  return <main className="catalog-page" aria-labelledby="inventory-operations-title"><header className="catalog-header"><div><button className="secondary-button" type="button" onClick={onBack}>← Overview</button><p className="eyebrow">Inventory operations</p><h1 id="inventory-operations-title">Move stock safely</h1><p className="muted">Use guided operations for receipts, issues, adjustments, and transfers. The server remains authoritative for stock validation.</p></div><span className={`status-badge ${canWrite ? "good" : ""}`}>{canWrite ? "Write access" : "Read only"}</span></header>
    <section className="inventory-op-layout"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">Operation</p><h2>Choose the stock action</h2></div></div><div className="operation-tabs" role="tablist" aria-label="Inventory operation type">{(["stock_in","stock_out","adjustment","transfer"] as Operation[]).map((value) => <button key={value} className={operation === value ? "operation-tab active" : "operation-tab"} type="button" onClick={() => setOperation(value)}>{labelFor(value)}</button>)}</div>
      <form className="catalog-form" onSubmit={submit}><div className="form-grid"><label><span>Product</span><select value={productId} onChange={(event) => setProductId(event.target.value)} disabled={state !== "ready" || saving}><option value="">Select product</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name} ({product.sku})</option>)}</select></label><label><span>{quantityLabel}</span><input type="number" min={operation === "adjustment" ? undefined : 1} step="1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} disabled={saving} /></label>{operation !== "transfer" ? <label><span>Location</span><select value={locationId} onChange={(event) => setLocationId(event.target.value)} disabled={state !== "ready" || saving}><option value="">Select location</option>{locations.map((location) => <option value={location.id} key={location.id}>{location.name} ({location.code}) — {warehouseById.get(location.warehouseId) ?? "Warehouse"}</option>)}</select></label> : <><label><span>From location</span><select value={fromLocationId} onChange={(event) => setFromLocationId(event.target.value)} disabled={state !== "ready" || saving}>{locations.map((location) => <option value={location.id} key={location.id}>{location.name} ({location.code})</option>)}</select></label><label><span>To location</span><select value={toLocationId} onChange={(event) => setToLocationId(event.target.value)} disabled={state !== "ready" || saving}>{locations.map((location) => <option value={location.id} key={location.id}>{location.name} ({location.code})</option>)}</select></label></>}<label><span>Reference</span><input value={reference} onChange={(event) => setReference(event.target.value)} maxLength={200} placeholder="PO, invoice, or ticket" disabled={saving} /></label></div><label><span>Note</span><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={4} maxLength={1000} placeholder="Optional operational context" disabled={saving} /></label>{message && <p className="form-error" role="status">{message}</p>}<div className="form-actions"><button className="primary-button" type="submit" disabled={saving || state !== "ready" || !canWrite}>{saving ? "Recording…" : labelFor(operation)}</button></div></form></article>
      <aside className="panel inventory-op-summary" aria-label="Operation summary"><div className="panel-heading"><div><p className="eyebrow">Review</p><h2>Before you submit</h2></div></div><dl><div><dt>Product</dt><dd>{selectedProduct ? `${selectedProduct.name} · ${selectedProduct.sku}` : "Not selected"}</dd></div><div><dt>Action</dt><dd>{labelFor(operation)}</dd></div><div><dt>{operation === "adjustment" ? "Delta" : "Quantity"}</dt><dd>{Number.isFinite(quantity) ? quantity.toLocaleString() : "—"} {selectedProduct?.unit ?? "units"}</dd></div>{operation !== "transfer" ? <div><dt>Location</dt><dd>{selectedLocation ? selectedLocation.name : "Not selected"}</dd></div> : <div><dt>Route</dt><dd>{locations.find((item) => item.id === fromLocationId)?.name ?? "—"} → {locations.find((item) => item.id === toLocationId)?.name ?? "—"}</dd></div>}</dl><p className="muted">Stock-out and transfer operations can fail when the server detects insufficient available stock. Do not retry blindly after an uncertain network response.</p></aside></section></main>;
}

function labelFor(operation: Operation) { switch (operation) { case "stock_in": return "Stock in"; case "stock_out": return "Stock out"; case "adjustment": return "Adjust stock"; case "transfer": return "Transfer stock"; } }
